### ISSUE TITLE
Is there way to convert any field type to string?

### ISSUE THREAD

**Issue by rualark** [discoveryjs/jora#18]

**Comment by lahmatiy** [comment]
Like in javascript, just concat with empty string: `anything + ''` or `'' + anything`

**Comment by lahmatiy** [comment]
Casting to a type may be implemented, but the question is about syntax for that

**Comment by rualark** [comment]
Thanks. I am just starting to discover jora :)
I see that I can sort then like this:

```
Data.match.({ID}).sort(('' + ID) asc)
```
