### ISSUE TITLE
Is there a way to force showing some fields first?

### ISSUE THREAD

**Issue by rualark** [discoveryjs/jora#19]
Example: having large json like
[
  {a: 1, b: 2, c: 3, d: 4, e: 5 .... },
  {a: 1, b: 2, c: 3, d: 4, e: 5 .... }
]

Some fields are hidden, because there are lots of them.
Only particular fields can be shown with ({g, h}), but is there way to show g and h fields first and then the others? Like first(g, h). Output:

[
  {g: 10, h: 11, a: 1, b: 2, c: 3, d: 4, e: 5 .... },
  {g: 12, h: 33, a: 1, b: 2, c: 3, d: 4, e: 5 .... }
]

If objects are sorted by key, then first output forced fields and then sort the rest.

**Comment by rualark** [comment]
Maybe this syntax can be used:

`.({g, h, *})`

**Comment by lahmatiy** [comment]
Yeah, your solution is correct, but use `...` instead of `*`

**Comment by rualark** [comment]
Ohh, that's cool! Thanks a lot!
Am I missing some page with examples? I saw README, but it is not easy to understand without examples.

**Comment by lahmatiy** [comment]
Unfortunately, there is no examples page. I believe such pages appear soon.
Can we close the issue?
