### ISSUE TITLE
Proposal: add online sandbox with intellisense / autofill

### ISSUE THREAD

**Issue by irustm** [discoveryjs/jora#7]
|  data |  input | result  | 
|---|---|---|
|  ...  |  jora function  | []  |

**Comment by lahmatiy** [comment]
It’s a good idea! I think we can use discoveryjs in model-free mode for this with a few improvements. I suppose you want to paste json as a text not as a file? May be I missed something?

**Comment by irustm** [comment]
yeah, 
json as a text

**Comment by lahmatiy** [comment]
A simple sandbox is available as [discoveryjs/jora-sandbox](https://github.com/discoveryjs/jora-sandbox) repo or you can [try it online](https://discoveryjs.github.io/jora-sandbox/).
